### ISSUE TITLE
Killing one college kills them all

### ISSUE THREAD

**Issue by stanbsky** [stanbsky/How-Hard-Can-It-Be-Redux#12]
Exactly what it says: when you shoot and kill any one college, they all die and game is won.

**Comment by Kroojel** [comment]
It seems that the college death being checked is tied to the disposal of the college. The college is not being correctly disposed of, therefore it continually runs the death script ending the game early.

**Comment by Kroojel** [comment]
College.java method 'dispose()' should actually deal with the object in some capacity

**Comment by Kroojel** [comment]
Added "collegeBodiesToRemove.add(college);" line to the death of a college. While this fixed the issue raised, I'm not sure if this is the best method for dealing with it.
