### ISSUE TITLE
Cannonballs collide with islands

### ISSUE THREAD

**Issue by abi-greeen** [stanbsky/How-Hard-Can-It-Be-Redux#16]
box 2d collision makes cannonball collide with island, needs to not happen

**Comment by stanbsky** [comment]
Hint: something needs changing in the maskBits! 😉

**Comment by stanbsky** [comment]
Had to fix it in 066b8453857373bad253a960dd0b4f29cf96f357, refactoring the whole thing in the process, because the "masks" as implemented were utterly ridiculous and not conducive to implementing new functionality, i.e. chests.
