### ISSUE TITLE
Doubled up input handler

### ISSUE THREAD

**Issue by Kroojel** [stanbsky/How-Hard-Can-It-Be-Redux#2]
Input handlers in both 'MainGameScreen' and 'Ship'.
We only need one set and the version in Ship looks awful.

**Comment by Kroojel** [comment]
Fixed input handler in ship to be much cleaner, should now be much easier to set up a single input handler

**Comment by stanbsky** [comment]
I've merged your changes with mine and into the main branch. If everything to do with refactoring input handler is done, feel free to close this issue (we can reopen later if need be).
