### ISSUE TITLE
Boss quest: fit for purpose, but could be better with bugs fixed

### ISSUE THREAD

**Issue by stanbsky** [stanbsky/How-Hard-Can-It-Be-Redux#33]
Boss quest is implemented in 44f2dd2a1aa2ab5d4b03301339465efbd9a22780 and is sufficient. There are some niggling issues though:

- Triple shot doesn't work: bullets get stuck inside the boss ship. Uncomment `Boss::bossShotReady()` to observe.
- Killing the boss too quick appears to crash on game win screen. ~~I suspect this has something to do with `currentQuest.dispose()`: calling an early `return;` after quest completion seems to prevent this, but more testing could be useful to make sure it's not a coincidence.~~

**Comment by stanbsky** [comment]
Nope! Still seems to crash on game over screen intermittently.

**Comment by Kroojel** [comment]
I'll take a look, but no promises that I can fix it

**Comment by Kroojel** [comment]
It isn't the boss, it's the checkForGameOver function in quests

**Comment by Kroojel** [comment]
Removed this.dispose() from the MainGameScreen.gameOver. This has fixed the issue for the time being

**Comment by Kroojel** [comment]
Boss shot has no timer, 30 bullets spawn concurrently

**Comment by Kroojel** [comment]
Fixed, the bullets now fire as triples
