### ISSUE TITLE
Textures corrupt when sliced into frames in GIMP

### ISSUE THREAD

**Issue by stanbsky** [stanbsky/How-Hard-Can-It-Be-Redux#7]
GIMP seems to sporadically corrupt colours in its exported PNGs. See the difference in two sequential frames exported from the same PNG input file after slicing:
![player06_1](https://user-images.githubusercontent.com/2092058/161173111-1819af19-6289-4a6d-860e-40392759988e.png)
![player6_2](https://user-images.githubusercontent.com/2092058/161173113-9f43382a-940d-4a6e-bc57-45390613a6ef.png)

Hopefully someone with access to Photoshop (@Jarredino ?) or another similar program can help me with this. I can guide how to do this in Photoshop if needed.

**Comment by Kroojel** [comment]
Unsplit textures were in an unfamiliar file format for gimp, changing the format to 'RGBA' PNG files fixed the issue. Attached are simple programs to fix this issue and automatically split the files.
[rgba + splitter.zip](https://github.com/stanbsky/How-Hard-Can-It-Be-Redux/files/8426758/rgba.%2B.splitter.zip)
